Eshop.Web/Models/Cart.cs
using Eshop.Models.BusinessDomains;
using Microsoft.AspNetCore.Mvc;
//using Eshop.Web.Binder;

namespace Eshop.Web.Models
{
    //[ModelBinder(BinderType = typeof(CartModelBinder))]
    public class Cart
    {
        private List<CartLine> lineCollection = new List<CartLine>();

        //adding items to ta cart list
        public void AddItem(Product product, int quantity)
        {
            var line = lineCollection.Where(p => p.Product.AutoId == product.AutoId).FirstOrDefault();
            if (line == null)
            {
                lineCollection.Add(new CartLine { Product = product, Quantity = quantity });
            }
            else
            {
                line.Quantity += quantity;
            }
        }
        //removing items from the cart list
        public void RemoveLine(Product product)
        {
            lineCollection.RemoveAll(l => l.Product.AutoId == product.AutoId);
        }
        public double ComputeTotalValue()
        {
            return lineCollection.Sum(e => e.Product.Price * e.Quantity);
        }
        // clearing the cart list
        public void Clear()
        {
            lineCollection.Clear();
        }
        public IEnumerable<CartLine> Lines
        {
            get { return lineCollection; }
        }
        public class CartLine
        {
            public Product Product { get; set; }
            public int Quantity { get; set; }
        }

    }
}

Eshop.Web/Controllers/BusinessDomains/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Eshop.Web.Data;
using Eshop.Web.Helper;
using Eshop.Models.BusinessDomains;
using Eshop.Utils;
using Eshop.Web.Controllers.Common;
using Eshop.ViewModels.BusinessDomains;
using Eshop.Interfaces.BusinessDetails;

namespace Eshop.Web.Controllers.BusinessDomains
{
    [Authorize]
    public class CartController(ApplicationDbContext context, IOrderProcessor orderProcessor) : BaseController
    {
        public ViewResult Index(Cart cart, string returnUrl)
        {
            CartIndexViewModel cartIndex = new()
            {
                Cart = cart,
                ReturnUrl = returnUrl,
            };
            return View(cartIndex);

        }

        //adding new items to the cart
        public async Task<IActionResult> AddToCart(Cart cart, int productId, string returnUrl)
        {
            Product? product = await context.Products.Include(c => c.Category).FirstOrDefaultAsync(p => p.AutoId == productId);
            if (product != null)
            {
                try
                {
                    var _cart = cart.Lines.Where(x => x.Product.AutoId == product.AutoId).FirstOrDefault();
                    if (_cart != null && _cart.Quantity >= product.CurrentStock)
                    {
                        TempData["Error"] = "Sorry! All stock has been added.";
                    }
                    else if (product.CurrentStock == 0)
                    {
                        TempData["Error"] = "Sorry! This product is out of stock.";
                    }
                    else
                    {
                        cart.AddItem(product, 1);
                        HttpContext.Session.SetInt32(Constant.CartTotal, cart.Lines.Sum(x => x.Quantity));
                        ViewData["CartTotal"] = HttpContext.Session.GetInt32(Constant.CartTotal);
                        HttpContext.Session.SetObjectAsJson<Cart>(Constant.CART, cart);
                        TempData["Success"] = "Added to the cart successfully";
                    }
                }
                catch (Exception ex)
                {
                    TempData["Error"] = "Error raised. The error is " + ex.Message;
                }

            }
            CartIndexViewModel cartIndex = new()
            {
                Cart = cart,
                ReturnUrl = returnUrl,
            };
            return View(nameof(Index), cartIndex);
        }


        //removing an item from cart 
        public async Task<IActionResult> RemoveFromCart(Cart cart, int productId, string returnUrl)
        {
            Product? product = await context.Products.Include(c => c.Category).FirstOrDefaultAsync(p => p.AutoId == productId);
            if (product != null)
            {
                try
                {
                    cart.RemoveLine(product);

                    HttpContext.Session.SetInt32(Constant.CartTotal, cart.Lines.Sum(x => x.Quantity));
                    ViewData["CartTotal"] = HttpContext.Session.GetInt32(Constant.CartTotal);
                    HttpContext.Session.SetObjectAsJson<Cart>(Constant.CART, cart);
                    TempData["Success"] = "Removed successfully";
                }
                catch (Exception ex)
                {
                    TempData["Error"] = "Error raised. The error is " + ex.Message;
                }
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        // my total cart details
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }


        //Shipping Details
        public ViewResult Checkout(Cart cart)
        {
            ShippingDetails shippingDetails = new()
            {
                IsConfirmed = false,
                CreatedBy = CurrentUserName,
                CreatedDate = DateTime.Today
            };
            if (cart.Lines.Count() == 0)
            {
                ViewData["EmptyCart"] = "True";
            }
            return View(shippingDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            ShipmentOrders shipmentOrders = new();
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    await context.ShippingDetails.AddAsync(shippingDetails);
                    await context.SaveChangesAsync();
                    foreach (var i in cart.Lines)
                    {
                        shipmentOrders.AutoId = null;
                        shipmentOrders.ShippingDetailsId = shippingDetails.AutoId;
                        shipmentOrders.Quantity = i.Quantity;
                        shipmentOrders.ProductName = i.Product.Name;
                        shipmentOrders.ProductId = i.Product.AutoId;
                        shipmentOrders.CategoryId = i.Product.CategoryId;
                        shipmentOrders.Price = (float)(i.Product.Price * i.Quantity);
                        shipmentOrders.CreatedBy = shippingDetails.CreatedBy;
                        shipmentOrders.CreatedDate = shippingDetails.CreatedDate;

                        await context.ShipmentOrders.AddAsync(shipmentOrders);
                        await context.SaveChangesAsync();
                    }

                    await orderProcessor.ProcessOrder(cart, shippingDetails);
                    cart.Clear();

                    TempData["Success"] = "Mail has been sent successfully.";
                    HttpContext.Session.Remove(Constant.CART);
                    HttpContext.Session.Remove(Constant.CartTotal);
                    HttpContext.Session.Remove(Constant.PENDING_ORDERS);

                    return View("Completed");
                }
                catch (Exception ex)
                {
                    TempData["Error"] = "Failed!Something went wrong! " + ex.Message;
                    return View(shippingDetails);
                }
            }
            else
            {
                return View(shippingDetails);
            }
        }
        protected override void Dispose(bool disposing)
        {
            context.Dispose();
            base.Dispose(disposing);
        }
    }
}

Eshop.Web/Controllers/BusinessDomains/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Eshop.Web.Data;
using Eshop.Web.Models;
using Eshop.Models.BusinessDomains;
using Eshop.Web.Controllers.Common;

namespace Eshop.Web.Controllers.BusinessDomains
{
    [Authorize]
    public class CategoryController : BaseController
    {
        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Category
        public async Task<IActionResult> Index()
        {
            return _context.Category != null ?
                        View(await _context.Category.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Category'  is null.");
        }

        // GET: Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Category == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.AutoId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Category/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                category.CreatedBy = CurrentUserName;
                category.CreatedDate = DateTime.Now;

                _context.Add(category);
                await _context.SaveChangesAsync();

                TempData["Success"] = "Saved Successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Category == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AutoId,CategoryName,CreatedBy,CreatedDate")] Category category)
        {
            if (id != category.AutoId)
            {
                return NotFound();
            }

            try
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        category.CreatedBy = CurrentUserName;
                        category.CreatedDate = DateTime.Now;

                        _context.Update(category);
                        await _context.SaveChangesAsync();

                        TempData["Success"] = "Updated Successfully";
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!CategoryExists(category.AutoId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                TempData["Error"] = "Somthing Went Wrong";
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Category == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.AutoId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Category == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Category'  is null.");
            }
            var category = await _context.Category.FindAsync(id);
            if (category != null)
            {
                try
                {
                    _context.Category.Remove(category);
                    await _context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    TempData["Error"] = "Sorry! Failed to remove. Message : " + ex.Message;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return (_context.Category?.Any(e => e.AutoId == id)).GetValueOrDefault();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
            base.Dispose(disposing);
        }
    }
}

Eshop.Web/Controllers/PaymentController.cs
using Braintree;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Eshop.Web.Common;
using Eshop.Web.Data;
using Eshop.Web.Helper;
using Eshop.Web.Interfaces;
using Eshop.Web.Models;
using Eshop.Web.Models.ViewModels;
using Eshop.Utils;

namespace Eshop.Web.Controllers
{
    public class PaymentController : BaseController<PaymentController>
    {
        private readonly IBraintreeService _braintreeService;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        
        public PaymentController(ApplicationDbContext context, UserManager<ApplicationUser> userManager, IBraintreeService braintreeService)
        {
            _userManager = userManager;
            _context = context;
            _braintreeService = braintreeService;
        }
        public IActionResult Index(Cart cart)
        {
            var gateway = _braintreeService.GetGateway();
            var clientToken = gateway.ClientToken.Generate();  //Genarate a token
            ViewData["ClientToken"] = clientToken;

            CartIndexViewModel cartIndex = new CartIndexViewModel
            {
                Cart = cart
            };
            return View(cartIndex);
        }
        [HttpPost]
        public async Task<IActionResult> Create(CartIndexViewModel model)
        {
            var usr = await _userManager.GetUserAsync(HttpContext.User);
            var gateway = _braintreeService.GetGateway();
            var customer = new CustomerRequest { 
                FirstName = usr?.FirstName,
                LastName = usr?.LastName,
                Email = usr?.Email,
                Id = usr?.Id,
                Phone = usr?.PhoneNumber
            };
            var request = new TransactionRequest
            {
                Amount = Convert.ToDecimal(model.Cart.ComputeTotalValue()),
                PaymentMethodNonce = model.Nonce,
                Customer = customer,
                Options = new TransactionOptionsRequest
                {
                    SubmitForSettlement = true
                }
            };

            Result<Transaction> result = gateway.Transaction.Sale(request);

            if (result.IsSuccess())
            {
                model.Cart.Clear();
                HttpContext.Session.SetInt32(Constant.CartTotal, model.Cart.Lines.Sum(x => x.Quantity));
                ViewData["CartTotal"] = HttpContext.Session.GetInt32(Constant.CartTotal);
                SessionHelper.SetObjectAsJson<Cart>(HttpContext.Session, Constant.CART, model.Cart);

                return await Task.FromResult(View("Success"));
            }
            else
            {
                TempData["Error"] = "Failed! Something went wrong.";
                return await Task.FromResult(View("Index", model));
            }
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
            base.Dispose(disposing);
        }
    }
}

Eshop.Web/Views/BusinessDomains/Cart/Checkout.cshtml
@model Eshop.Models.BusinessDomains.ShippingDetails

@{
    ViewBag.Title = "Eshop.Web: Checkout";
}

<h2>Checkout Now</h2>
<p>Please enter your details, and we'll ship your goods right away!</p>

@using (Html.BeginForm())
{
    @Html.ValidationSummary()
    @Html.HiddenFor(x=>x.CreatedBy)
    @Html.HiddenFor(x=>x.CreatedDate)
    <h3>Ship to</h3>
    <div class="form-group">
        <label>Name:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = " form-control " })
    </div>

    <h3>Address</h3>

    @*<div class="form-group">
        <label>Line 1:</label>
        @Html.TextBoxFor(x => x.Line1, new { @class = " form-control " })
    </div>
    <div class="form-group">
        <label>Line 2:</label>
        @Html.TextBoxFor(x => x.Line2, new { @class = " form-control " })
    </div>
    <div class="form-group">
        <label>Line 3:</label>
        @Html.TextBoxFor(x => x.Line3, new { @class = " form-control " })
    </div>
    <div class="form-group">
        <label>City:</label>
        @Html.TextBoxFor(x => x.City, new { @class = " form-control " })
    </div>
    <div class="form-group">
        <label>State:</label>
        @Html.TextBoxFor(x => x.State, new { @class = " form-control " })
    </div>
    <div class="form-group">
        <label>Zip:</label>
        @Html.TextBoxFor(x => x.Zip, new { @class = " form-control " })
    </div>
    <div class="form-group">
        <label>Country:</label>
        @Html.TextBoxFor(x => x.Country, new { @class = " form-control " })
    </div>*@

    foreach ( var property in ViewData.ModelMetadata.Properties)
                {
        if (property.PropertyName != "NAME" && property.PropertyName != "GIFTWRAP" && property.PropertyName != "AutoId" && property.PropertyName != "IsConfirmed" && property.PropertyName != "CreatedBy" && property.PropertyName != "CreatedDate" && property.PropertyName != "CONFIRM_BY" && property.PropertyName != "CONFIRM_DATE")
                    {
                        <div class="form-group">
                            <label>@(property.DisplayName ?? property.PropertyName)</label>
                            @Html.TextBox(property.PropertyName, null, new {@class = " form-control "})
                        </div>                          
                    }
                }

    <h3>Options</h3>
    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(x=>x.Giftwrap, htmlAttributes: new {  @class="form-check-input" })
            Gift wrap this items
        </label>
    </div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Complete order" id="COrder" />
    </div>
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script type="text/javascript">
        $("#COrder").click(function (event) {
            var EmptyStatus = "@ViewBag.EmptyCart";

            //alert(EmptyStatus);
            var IsEmpty = EmptyStatus == "True" ? true : false;
            if(IsEmpty){
                alert("Sorry! Your cart is empty");
                event.preventDefault();
            }
        });
    </script>
}

Eshop.Web/Views/BusinessDomains/Cart/Completed.cshtml
@{
    ViewBag.Title = "Eshop.Web: Order Submitted";
}

<h2>Thanks! @User.Identity?.Name</h2>
Thanks for placing your order. We'll ship your goods as soon as possible.
<div>
    <a asp-area="" asp-controller="Product" asp-action="Index">Back to home</a>
</div>

Eshop.Web/Views/BusinessDomains/Cart/Index.cshtml
@model Eshop.ViewModels.BusinessDomains.CartIndexViewModel

@{
    ViewBag.Title = "Sports Store: Your Cart";
}
<style>
    #cartTable td { vertical-align:middle; }
</style>

<h2>Your cart</h2>
<table id="cartTable" class="table">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="text-right">Price</th>
            <th class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
        <tr>
            <td class="text-center">@line.Quantity</td>
            <td class="text-left">@line.Product.Name</td>
            <td class="text-right">@line.Product.Price.ToString("c")</td>
            <td class="text-right">@((line.Quantity * line.Product.Price).ToString("c"))</td>
            <td>
                @using (Html.BeginForm("RemoveFromCart", "Cart"))
                {
                    @Html.Hidden("productId", line.Product.AutoId)
                    @Html.HiddenFor(x => x.ReturnUrl)
                    <input class="btn btn-sm btn-warning" type="submit" value="Remove" />
                }
            </td>
        </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Total:</td>
            <td class="text-right">@Model.Cart.ComputeTotalValue().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    @if (Model.ReturnUrl != null)
    {
        <a class="btn btn-info" href="@Model.ReturnUrl">Continue Shopping</a>
    }
    else
    {
        <a class="btn btn-info" asp-area="" asp-controller="Product" asp-action="Index">Continue Shopping</a>
    }
    @Html.ActionLink("Checkout Now","Checkout", "Cart", null, new {@class=" btn btn-info "})
    @Html.ActionLink("Pay Now","Index", "Payment", null, new {@class=" btn btn-info "})
</div>

Eshop.Web/Views/BusinessDomains/Cart/Summary.cshtml
@model Eshop.ViewModels.BusinessDomains.Cart

<div class="navbar-right hidden-xs">
    @Html.ActionLink("Checkout","Index","Cart",
    new { returnUrl=@Context.Request.Path },
    new { @class = "btn btn-default navbar-btn" }
    )
</div>
<div class="navbar-right visible-xs">
    <a href=@Url.Action("Index","Cart", new { returnUrl = @Context.Request.Path })
       class="btn btn-default navbar-btn">
        <span class="glyphicon glyphicon-shopping-cart"></span>
    </a>
</div>
<div class="navbar-text navbar-right">
    <b class="hidden-xs">Your cart:</b>
    @Model.Lines.Sum(x=>x.Quantity) item(s),
    @Model.ComputeTotalValue().ToString("c")
</div>